version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build-dist:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run-script build
      - save_cache:
          key: dist-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - src/.vuepress/dist

  build-docker:
    docker:
      - image: glenathan/circleci-kaniko:build-65
    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build dir
          command: mkdir -p /kaniko/.docker
      - run:
          name: Auth setup
          command: echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - run:
          name: Test
          command: cat /kaniko/.docker/config.json ; echo $CIRCLE_WORKING_DIRECTORY
      - run:
          name: BuildImage
          command: >-
            /kaniko/executor
            --context $CIRCLE_WORKING_DIRECTORY
            --dockerfile $CIRCLE_WORKING_DIRECTORY/DockerFile
            --destination $CI_REGISTRY/salsa:latest
workflows:
  sample:
    jobs:
      - build-dist
      - build-docker:
          filters:
            branches:
              only:
                - master
          requires:
            - build-dist

