version: 2.1

orbs:
  node: circleci/node@4.1
  kaniko-publish: freeletics/kaniko-publish@0.2.0

jobs:
  build-dist:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run-script build
      - save_cache:
          key: dist-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - src/.vuepress/dist

workflows:
  sample:
    jobs:
      - build-dist
      - kaniko-publish/publish:
          registry: registry.crip.conacyt.mx
          image: conacyt-arquitectura/salsa
          tag: latest 
          before_build:
            - restore_cache:
                keys:
                  - dist-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          filters:
            branches:
              only:
                - master
          requires:
            - build-dist
