module.exports.AvatarModel = {
    isCircle: false,
    circleColor: "#5e4934",
    accessoriesType: "Blank",
    clotheType: "ShirtCrewNeck",
    clotheColor: "Black",
    eyebrowType: "Default",
    eyeType: "Default",
    facialHairColor: "Brown",
    facialHairType: "Blank",
    graphicType: "Skull",
    hairColor: "BrownDark",
    mouthType: "Default",
    skinColor: "Pale",
    topType: "NoHair",
    topColor: "Blue03",
}